// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69baFakRCLam02nZeCVS1EyNntNqMTdw',
    appId: '1:59809875158:android:5e490aea71959867803577',
    messagingSenderId: '59809875158',
    projectId: 'task-management-ac75f',
    storageBucket: 'task-management-ac75f.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1MZSRbPA0UUn34p4cV85j3XnzjZ2eQE',
    appId: '1:59809875158:web:98b792b01f4cb286803577',
    messagingSenderId: '59809875158',
    projectId: 'task-management-ac75f',
    authDomain: 'task-management-ac75f.firebaseapp.com',
    storageBucket: 'task-management-ac75f.appspot.com',
    measurementId: 'G-GX6MHLBDVF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJirNAgOXh4Tgy8b9lOJqVn3Sdnt6E9Dg',
    appId: '1:59809875158:ios:3976b626b5c7e9dd803577',
    messagingSenderId: '59809875158',
    projectId: 'task-management-ac75f',
    storageBucket: 'task-management-ac75f.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJirNAgOXh4Tgy8b9lOJqVn3Sdnt6E9Dg',
    appId: '1:59809875158:ios:3976b626b5c7e9dd803577',
    messagingSenderId: '59809875158',
    projectId: 'task-management-ac75f',
    storageBucket: 'task-management-ac75f.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH1MZSRbPA0UUn34p4cV85j3XnzjZ2eQE',
    appId: '1:59809875158:web:a15f086205c57dec803577',
    messagingSenderId: '59809875158',
    projectId: 'task-management-ac75f',
    authDomain: 'task-management-ac75f.firebaseapp.com',
    storageBucket: 'task-management-ac75f.appspot.com',
    measurementId: 'G-Y5F6BX6SJZ',
  );

}